version: '3.5'

services:

    laravel_app:
        image: webdevops/php-nginx:8.0
        container_name: laravel_app
        environment:
            WEB_DOCUMENT_ROOT: /app/public
            PHP_DATE_TIMEZONE: America/Guayaquil
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - "80:80"

    postgres:
        image: postgres:14-alpine
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:6
        depends_on:
            - postgres
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: username@example.com
            PGADMIN_DEFAULT_PASSWORD: postgres
        ports:
            - "8080:80"
